#include<iostream.h>
#include<conio.h>

void main()
{
	int a=10;
	int b=5;

	clrscr();


	cout<<"\n\t\tArithmetic Operators\n";
	cout<<"\na+b = "<<(a+b);
	cout<<"\na-b = "<<(a-b);
	cout<<"\na*b = "<<(a*b);
	cout<<"\na/b = "<<(a/b);

	cout<<"\n\t\tRelational Operators\n";
	cout<<"\na>b is "<<(a>b);
	cout<<"\na<b is "<<(a<b);
	cout<<"\na==b is "<<(a==b);
	cout<<"\na!=b is "<<(a!=b);
	cout<<"\na>=b is "<<(a>=b);
	cout<<"\na<=b is "<<(a<=b);

	getch();
}